#!/bin/bash
# Quick test script for production pipeline
# This tests: Mock PLC Agent → MQTT (TLS) → InfluxDB Writer → InfluxDB → Grafana

echo "🧪 Testing Production Pipeline"
echo "================================"
echo ""
echo "Services needed:"
echo "  ✅ MQTT Broker (Docker) - Should be running"
echo "  ✅ InfluxDB (Docker) - Should be running"
echo "  ✅ Grafana (Docker) - Should be running"
echo ""
echo "To test:"
echo ""
echo "1. Terminal 1 - Run Mock PLC Agent (Publisher):"
echo "   cd /Users/khanhamza/mqtt-ot-network"
echo "   export MQTT_BROKER_HOST=localhost"
echo "   export MQTT_BROKER_PORT=8883"
echo "   export MQTT_USERNAME=edge_gateway"
echo "   export MQTT_PASSWORD=edge_gateway_pass"
echo "   export MQTT_TLS_ENABLED=true"
echo "   export MQTT_TLS_CHECK_HOSTNAME=false"
echo "   export CA_CERT_PATH=mosquitto/config/certs/ca.crt"
echo "   export CLIENT_CERT_PATH=mosquitto/config/certs/client.crt"
echo "   export CLIENT_KEY_PATH=mosquitto/config/certs/client.key"
echo "   python3 mock_plc_agent/mock_plc_agent.py"
echo ""
echo "2. Terminal 2 - Run InfluxDB Writer (Subscriber):"
echo "   cd /Users/khanhamza/mqtt-ot-network"
echo "   export MQTT_BROKER_HOST=localhost"
echo "   export MQTT_BROKER_PORT=8883"
echo "   export MQTT_USERNAME=influxdb_writer"
echo "   export MQTT_PASSWORD=influxdb_writer_pass"
echo "   export MQTT_TLS_ENABLED=true"
echo "   export MQTT_TLS_CHECK_HOSTNAME=false"
echo "   export CA_CERT_PATH=mosquitto/config/certs/ca.crt"
echo "   export INFLUXDB_URL=http://localhost:8086"
echo "   export INFLUXDB_TOKEN=my-super-secret-auth-token"
echo "   export INFLUXDB_ORG=myorg"
echo "   export INFLUXDB_BUCKET=plc_data"
echo "   python3 influxdb_writer/influxdb_writer_production.py"
echo ""
echo "3. View in Grafana:"
echo "   http://localhost:3004"
echo "   Login: admin / admin"
echo ""

